---

- name: Ensure group "radmin" exists
  ansible.builtin.group:
    name: radmin
    state: present

- name: Adding existing user to group radmin "{{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"
    groups: radmin
    append: true

- name: Add R repository public key
  ansible.builtin.apt_key:
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - r-repository-public-key

- name: Add R repository
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }}"
    state: present
    update_cache: true
  with_items: "{{ r_repository }}"
  tags:
    - r-repository-add

- name: Install Packages
  ansible.builtin.apt:
    name: '{{ r_packages }}'
    state: latest

- name: Creates .Rprofile with default repo
  ansible.builtin.lineinfile:
    dest: /home/{{ username }}/.Rprofile
    line: 'local({r <- getOption("repos");r["CRAN"] <- "https://cloud.r-project.org";options(repos = r)})'
    create: true
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0600'

- name: Creates .Renviron with default lib path
  ansible.builtin.lineinfile:
    dest: /home/{{ username }}/.Renviron
    line: '#R_LIBS_SITE_USER==/home/{{ username }}/R/rpackages'
    create: true
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0600'

- name: Ensure /usr/local/lib/R/site-library/ is writable by radmin
  ansible.builtin.file:
    dest: /usr/local/lib/R/site-library/
    owner: root
    group: radmin
    mode: u=rwX,g=rwX,o=rX
    recurse: true
