---
- name: start iptables-persistent
  ansible.builtin.service: name=netfilter-persistent state=started

- name: restart iptables-persistent
  ansible.builtin.service: name=netfilter-persistent state=restarted
