# - name: Install Packages
#   apt: name="{{ item }}" state=latest
#   with_items:
#     - libfontconfig1:i386
#     - libx11-6:i386
#     - libxrender1:i386
#     - libxext6:i386
#     - libgl1-mesa-glx:i386
#     - libglu1-mesa:i386
#     - libglib2.0-0:i386
#     - libsm6:i386

- name: Install Google Key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Add Google Repo
  apt_repository: repo='deb http://dl.google.com/linux/earth/deb/ stable main'

- name: Install Packages
  apt: name="{{ item }}" state=latest
  with_items:
    - google-earth-stable
