---
- name: Add google APT repository
  ansible.builtin.deb822_repository:
    name: google
    types: [deb]
    uris:
      - "http://dl.google.com/linux/earth/deb"
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    suites: [stable]
    components: [main]
    state: present
    enabled: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Packages
  ansible.builtin.apt:
    state: latest
  with_items:
    - google-earth-pro-stable
