---
- name: Install Packages
  ansible.builtin.apt:
    pkg:
      - python3-virtualenvwrapper
      - python3-virtualenv
      - python3
      - python3-dev
      - python3-pip

      - acl
      - alacarte
      - apparmor
      - apparmor-profiles
      - apparmor-utils
      - aspell-es
      - audacious
      - basez
      - ca-certificates
      - chromium-browser
      - colordiff
      - coreutils
      - curl
      - direnv
      - ffmpeg
      - filezilla
      - firefox
      - firejail
      - flatpak
      - gcc
      - gdebi
      - gimp
      - gnupg
      - gpicview
      - hopenpgp-tools
      - htop
      - imagemagick
      - incron
      - inkscape
      - iptables-persistent
      - ispell
      - jpegoptim
      - jq
      - ledger
      - linux-tools-generic
      - locales
      - lynx
      - magic-wormhole
      - man-db
      - menulibre
      - myspell-es
      - nmap
      - openvpn
      - optipng
      - p7zip-full
      - p7zip-rar
      - parallel
      - piper
      - podman
      - poedit
      - postgresql-client
      - protobuf-compiler
      - proxychains
      - qpdfview
      - rename
      - ripgrep
      - shellcheck
      - shfmt
      - siege
      - silversearcher-ag
      - smartmontools
      - smplayer
      - software-properties-common
      - sox
      - spatialite-gui
      - sqlite3
      - sqlitebrowser
      - steghide
      - sudo
      - tarlz
      - telnet
      - tlp
      - tor
      - traceroute
      - typecatcher
      - unrar
      - unzip
      - viewnior
      - vim-gui-common
      - vim-runtime
      - vlc
      - wget
      - whois
      - xclip
      - xscreensaver
      - zip
      - zpaq
      - zsh

    #      - xubuntu-restricted-extras
    state: present

- name: Install firejail
  ansible.builtin.apt:
    pkg:
      - firejail
    state: latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '16.04'

# - name: pip install various utilities
#   pip:
#     name:
#       - setuptools
#       - virtualenvwrapper
#       - httpie
#       - magic-wormhole
#       - docker-compose
#     executable: pip3
#     extra_args: --user
#   become: yes
#   become_user: "{{ username }}"
