- name: Install Packages
  apt:
    pkg:
      - acl
      - aspell-es
      - audacious
      - ca-certificates
      - chromium-browser
      - colordiff
      - coreutils
      - curl
      - curl
      - filezilla
      - firefox
      - flatpak
      - gcc
      - gdebi
      - gimp
      - gnupg
      - gnupg
      - hopenpgp-tools
      - htop
      - imagemagick
      - imagemagick
      - inkscape
      - ispell
      - jpegoptim
      - jq
      - ledger
      - libavcodec-extra
      - libcairo2-dev
      - libffi-dev
      - libfreetype6-dev
      - libjq-dev
      - libmagick++-dev
      - libpoppler-cpp-dev
      - libprotobuf-dev
      - libssl-dev
      - libudunits2-dev
      - libxml2-dev
      - libxmlsec1-dev
      - locales
      - lynx
      - man-db
      - myspell-es
      - nano
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - openvpn
      - optipng
      - p7zip-full
      - p7zip-rar
      - parallel
      - poedit
      - protobuf-compiler
      - python3-dev
      - python3-libtorrent
      - python3-pip
      - python3-proselint
      - python3-sphinx
      - qbittorrent
      - qpdfview
      - rename
      - rhythmbox
      - shellcheck
      - siege
      - silversearcher-ag
      - smplayer
      - sox
      - spatialite-gui
      - sqlite3
      - sqlitebrowser
      - steghide
      - software-properties-common
      - sudo
      - telnet
      - tor
      - traceroute
      - typecatcher
      - unrar
      - unzip
      - vagrant
      - vim-gui-common
      - vim-runtime
      - virtualbox
      - virtualenvwrapper
      - vlc
      - wget
      - whois
      - xclip
      - xscreensaver
      - zip
      - zsh
#      - xubuntu-restricted-extras
    state: present

- apt:
    pkg:
      - firejail
    state: latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '16.04'

- name: pip install various utilities
  pip:
    name:
      - setuptools
      - virtualenvwrapper
      - httpie
      - magic-wormhole
      - docker-compose
    executable: pip3
    extra_args: --user
  become: yes
  become_user: "{{ username }}"
