---
- name: Prepare System for Installation
  hosts: all
  gather_facts: false

  tasks:
    - name: Install python
      ansible.builtin.raw: >
        test -e /usr/bin/python3 ||
        (apt -y update && apt install -y python3 python3-setuptools)
      register: myoutput
      changed_when: myoutput.rc != 0
    - name: Apt Update server
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Install required packages acl python3-pip
      ansible.builtin.apt:
        pkg:
          - acl
          - python3-pip
        state: latest

- name: Install System
  hosts: all
  vars:
    apps_dir: "bin"
    ansible_python_interpreter: /usr/bin/python3
    allow_world_readable_tmpfiles: true
    username: diego
    rstudio_url: https://download1.rstudio.org/electron/jammy/amd64/rstudio-2024.12.1-563-amd64.deb
    rstudio_arch: amd64 # i386
    # emacs_version: emacs
    keypassxc_version: 2.7.1
    nvm_version: v0.40.2
    borg_version: 1.2.8
    rclone_version: v1.69.1
    # electrum_version: 4.5.8
  roles:
    - keepassxc # check version
    - rclone # check architecture in tasks/rclone/vars/
    - emacs
    - vscode
    - virtualbox
    - R
    - r-studio
    - docker
    - gvisor
    - google-chrome
    - google-earth
    - iptables
    - incron
    # - apparmor
    - software
    - spanish
    - nvm
    - oh-my-zsh
    - zopfli
    - borg
    - brave
    - minisign
    - usbguard
    - macchanger
    - flatpak
    - tor-user
    # - electrum # check version
    # - unattended-upgrades
