---
- hosts: all
  gather_facts: False


  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-setuptools)
  - name: updates a server
    apt: allow_unauthenticated=yes update_cache=yes autoremove=yes autoclean=yes
#  - name: upgrade a server
#    apt: upgrade=dist

- hosts: all
  vars:
    username: diego
    postgre_version: 10
    postgis_version: 2.4
    appengine_url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-151.0.1-linux-x86_64.tar.gz #x86
    pycharm_version: 2018.3.4
    keypassxc_version: 2.3.4
    nvm_version: v0.34.0
    gephi_version: 0.9.2
    nodejs_version: "10.x"
    rclone_version: 1.46
    rclone_arch: amd64 # 386 # amd64
    rstudio_arch: amd64 # i386
    wikidpad_version: 2.2
    keypassx_version: 2.0.3
    dropbox_arch: x86_64 #x86 # x86_64
    borg_version: 1.1.1
    adobe_reader_url: http://ardownload.adobe.com/pub/adobe/reader/unix/9.x/9.5.5/enu/AdbeRdr9.5.5-1_i386linux_enu.deb
    adobe_source_code_pro_url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
    plex_download: https://downloads.plex.tv/plex-media-server/1.0.3.2461-35f0caa/plexmediaserver_1.0.3.2461-35f0caa_amd64.deb
    go_tarball: "go1.11.5.linux-amd64.tar.gz"
    go_tarball_checksum: "sha256:ff54aafedff961eb94792487e827515da683d61a5f9482f668008832631e5d25"
    electrum_url: https://download.electrum.org/3.3.4/Electrum-3.3.4.tar.gz
    rstudio_url: https://download1.rstudio.org/rstudio-xenial-1.1.463-amd64.deb
    filebot_url: 'https://get.filebot.net/filebot/FileBot_4.8.2/FileBot_4.8.2_amd64.deb'
    filebot_sha: 'https://get.filebot.net/filebot/FileBot_4.8.2/FileBot_4.8.2.pkg.sha256'
    filebot_sig: 'https://get.filebot.net/filebot/FileBot_4.8.2/FileBot_4.8.2_amd64.deb.asc'
  roles:
    - hosts
    - docker
    - apparmor
    - software
    - spanish
    - keepassxc
    - flexget
    - powerline-fonts
    #- fonts
    - nodejs
    - nvm
    - qgis
    - R
    - R-sf
    - r-studio
    - oh-my-zsh
    - rclone # check version and architecture
    - zopfli
    - youtube-dl
    #- opera
    - google-chrome
    - gmvault
    - virtualbox
    - unattended-upgrades
    - security
    - iptables
    - postgresql
    - borg
    #- plex
    - go
    - electrum
    - tor-browser
    - wikidpad
    - pycharm # check version
    - gephi # check version
    - filebot
    - vscode
    - atom
    - brave
    # google-earth
    # dnscrypt-proxy
    # appengine
    # firejail
