- name: Install Packages
  apt: name=unattended-upgrades state=latest

- name: Add Periodic Configuration
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root mode=644

- name: Add Unattended Upgrade Configuration
  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root  group=root mode=644
  notify:
   - Restart Unattended Upgrades
