---
- name: Checking that ssh directory exists
  stat:
    path: "/.ssh"
  register: ssh_config_dir
  changed_when: false

- name: Create ssh config directory if not exists
  file:
    path: "/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
  when: not ssh_config_dir.stat.exists

- name: Keep ssh connected
  lineinfile:
    dest: ".ssh/config"
    line: '{{ item }}'
  with_items:
    - "ServerAliveInterval 120"
    - "HashKnownHosts yes"
    - "HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256"

- name: ssh protocol and compression
  blockinfile:
    path: "/.ssh/config"
    block: |
      Host *
        Protocol 2
        Compression yes
