#https://github.com/trailofbits/algo/blob/master/roles/common/tasks/main.yml
- name: Restrict core dumps  using pam limits
  lineinfile: dest=/etc/security/limits.conf line="* hard core 0" state=present

- name: Restrict Core Dumps - using sysctl
  sysctl: name=fs.suid_dumpable value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present

- name: Disable Source Routed Packet Acceptance
  sysctl: name="{{item}}" value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
  notify:
    - flush routing cache
    
- name: Disable ICMP Redirect Acceptance
  sysctl: name="{{item}}" value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects  
    
- name: Disable Secure ICMP Redirect Acceptance
  sysctl: name="{{item}}" value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
  notify:
    - flush routing cache
  
- name: Enable Bad Error Message Protection
  sysctl: name=net.ipv4.icmp_ignore_bogus_error_responses value=1 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  notify:
    - flush routing cache
  
- name: Enable RFC-recommended Source Route Validation
  sysctl: name="{{item}}" value=1 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  notify:
    - flush routing cache
  
- name: Enable packet forwarding for IPv4
  sysctl: name=net.ipv4.ip_forward value=1
  
- name: Enable packet forwarding for IPv6
  sysctl: name=net.ipv6.conf.all.forwarding value=1    

- name: Do not send ICMP redirects (we are not a router)
  sysctl: name=net.ipv4.conf.all.send_redirects value=0
