- name: Install apt-transport-https packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https

- name: Add microsoft repository key
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc state=present

- name: Add vscode repository
  apt_repository: repo="deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" state=present

- name: Install vscode package
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - code
