---
- name: Install apt-transport-https packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - apt-transport-https

- name: Add VSCode APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    state: present
    enabled: true

- name: Install vscode package
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - code
