- name: install iptables-persistent
  apt: pkg=iptables-persistent state=present update_cache=true
  notify:
    - start iptables-persistent

# Add user

- name: Add the user 'anon'
  user:
    name: anon
    groups: audio
    shell: /bin/bash
    append: yes
    uid: 1634
    state: present

# Iptables

- name: Only tor
  lineinfile:
    owner: root 
    group: root 
    mode: 0644
    dest: /etc/iptables/rules.v4 
    line: "iptables -t nat -A OUTPUT -m owner --uid-owner 1634 -p tcp -j REDIRECT --to-ports 9040"
    insertbefore: '^COMMIT'
    state: present

- name: Only tor
  lineinfile:
    owner: root 
    group: root 
    mode: 644
    dest: /etc/iptables/rules.v4 
    line: "iptables -t nat -A OUTPUT -m owner --uid-owner 1634 -p tcp -j REDIRECT --to-ports 9040"
    insertbefore: '^COMMIT'
    state: present
    
- name: Only tor
  lineinfile:
    owner: root 
    group: root 
    mode: 0644
    dest: /etc/iptables/rules.v4 
    line: "iptables -t nat -A OUTPUT -m owner --uid-owner 1634 -p udp --dport 53 -j REDIRECT --to-ports 5300"
    insertbefore: '^COMMIT'
    state: present
    
- name: Only tor
  lineinfile:
    owner: root 
    group: root 
    mode: 0644
    dest: /etc/iptables/rules.v4 
    line: "iptables        -A OUTPUT -m owner --uid-owner 1634 -p udp -d 127.0.0.1 --dport 5300 -j ACCEPT"
    insertbefore: '^COMMIT'
    state: present
    
- name: Only tor
  lineinfile:
    owner: root 
    group: root 
    mode: 0644
    dest: /etc/iptables/rules.v4 
    line: "iptables        -A OUTPUT -m owner --uid-owner 1634 -j REJECT"
    insertbefore: '^COMMIT'
    state: present
    
- name: Only tor
  lineinfile:
    owner: root 
    group: root 
    mode: 0644
    dest: /etc/iptables/rules.v4 
    line: "COMMIT"
    state: present
      

- name: set firewall rules v4
  copy: src={{ iptables_file_v4 }} dest=/etc/iptables/rules.v4 owner=root group=root mode=644
  notify:
    - restart iptables-persistent

- name: set firewall rules v6
  copy: src={{ iptables_file_v6 }} dest=/etc/iptables/rules.v6 owner=root group=root mode=644
  notify:
    - restart iptables-persistent

- name: ensure iptables-persistent restarted
  service: name=netfilter-persistent state=restarted

# Tor

- name: tor package
  package:
    name: tor
    state: present

- name: configure tor to resolve onion hostnames
  blockinfile:
    path: /etc/iptables/rules.v4 
    owner: root 
    group: root 
    mode: 0644
    block: |
      TransPort 9040
      DNSPort 5300
      AutomapHostsOnResolve 1
      
- name: template torrc
  template: src=torrc dest=/etc/tor/torrc
    owner=root group=root mode=0644
  notify:
  - restart tor
  
- name: ensure tor is running
  service: name=tor state=running
