---
- name: Install iptables-persistent
  ansible.builtin.apt:
    pkg: iptables-persistent
    state: present
    update_cache: "true"
  changed_when: docker is undefined
  notify:
    - Start iptables-persistent

- name: Set firewall rules v4
  ansible.builtin.copy:
    src: "{{ iptables_file_v4 }}"
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "640"
  changed_when: docker is undefined
  notify:
    - Restart iptables-persistent

- name: Set firewall rules v6
  ansible.builtin.copy:
    src: "{{ iptables_file_v6 }}"
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: "640"
  changed_when: docker is undefined
  notify:
    - Restart iptables-persistent

- name: Ensure iptables-persistent restarted
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted
  when: docker is undefined
