---
- name: Install Packages
  apt: name=openjdk-8-jdk state=latest

- name: Create apps directory
  file: path=/home/{{ username }}/{{ apps_dir }}
    state=directory

- name: Remove gephi directory
  file: path=/home/{{ username }}/{{ apps_dir }}/gephi
    state=absent

- name: Create temp directory for downloading gephi
  command: mktemp -d /tmp/gephi.XXXXXX
  register: mktemp_output

- name: download gephi
  become: yes
  get_url:
    url: "https://github.com/gephi/gephi/releases/download/v{{ gephi_version }}/gephi-{{ gephi_version }}-linux.tar.gz"
    dest: "{{ mktemp_output.stdout }}/gephi.tar.gz"
    owner: root
    group: root
    mode: 0644

- name: untar gephi
  shell: "tar -xzf {{ mktemp_output.stdout }}/gephi.tar.gz -C /home/{{username}}/{{apps_dir}}/"

- name: Move gephi
  command: mv /home/{{username}}/{{apps_dir}}/gephi-{{ gephi_version }} /home/{{username}}/{{ apps_dir }}/gephi

- name: Gephi directory with proper permissions
  become: yes
  file: path=/home/{{ username }}/{{ apps_dir }}/gephi
    state=directory
    owner="{{username}}"
    recurse=yes
