# - name: Import the NodeSource GPG key into apt
#   apt_key:
#     id: 68576280
#     url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"

# - name: Add NodeSource deb repository
#   apt_repository:
#     repo: 'deb https://deb.nodesource.com/setup_{{ nodejs_version }} {{ ansible_distribution_release }} main'
#     state: present

# - name: Add NodeSource deb-src repository
#   apt_repository:
#     repo: 'deb-src https://deb.nodesource.com/setup_{{ nodejs_version }} {{ ansible_distribution_release }} main'
#     state: present

- name: Install nodejs from nodesource
  shell: curl -sL https://deb.nodesource.com/setup_{{ nodejs_version }} | sudo -E bash -
  args:
    warn: false

- name: Install Node.js
  apt:
    pkg:
      - nodejs
    state: present
    update_cache: yes

- name: Install simplehttpserver
  npm: name=simplehttpserver global=yes
