- name: Create temp directory for downloading keepassxc
  command: mktemp -d /tmp/keepassxc.XXXXXX
  register: mktemp_output

- name: directories for flexget
  shell: mkdir -p /home/{{ username }}/{{ apps_dir }}/

- name: Download keepassxc
  get_url:
    url: https://github.com/keepassxreboot/keepassxc/releases/download/{{ keypassxc_version }}/KeePassXC-{{ keypassxc_version }}-x86_64.AppImage
    dest: "/home/{{ username}}/{{ apps_dir }}/keepassxc.Appimage"
    checksum: "sha256:https://github.com/keepassxreboot/keepassxc/releases/download/{{ keypassxc_version }}/KeePassXC-{{ keypassxc_version }}-x86_64.AppImage.DIGEST"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"

- name: Download keepassxc signature
  get_url:
    url: https://github.com/keepassxreboot/keepassxc/releases/download/{{ keypassxc_version }}/KeePassXC-{{ keypassxc_version }}-x86_64.AppImage.sig
    dest: "{{ mktemp_output.stdout }}/keepassxc.sig"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"

- name: Get GPG key
  shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys CFB4C2166397D0D2 ||
    gpg --keyserver pgp.mit.edu --recv-keys CFB4C2166397D0D2 ||
    gpg --keyserver keyserver.ubuntu.com --recv-keys CFB4C2166397D0D2

- name: Verify downloaded archive
  command: gpg --verify keepassxc.sig "/home/{{ username}}/apps/keepassxc.Appimage" chdir={{ mktemp_output.stdout }}

