---
- name: Start iptables-persistent
  ansible.builtin.service:
    name: netfilter-persistent
    state: started

- name: Restart iptables-persistent
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted

- name: Restart tor
  ansible.builtin.service:
    name: tor
    state: restarted
