- name: Create temp directory for downloading zopfli
  command: mktemp -d /tmp/zopfli.XXXXXX
  register: mktemp_output

- name: check installed
  command: /usr/local/bin/zopfli -h
  register: result
  ignore_errors: True
  changed_when: False

- name: Clone zopfli repo
  git: repo=https://github.com/google/zopfli dest={{ mktemp_output.stdout }} force=yes
  when: result.rc != 0

- name: make
  command: make -j{{ ansible_processor_cores }} chdir={{ mktemp_output.stdout }}
  when: result.rc != 0

- name: install
  shell: if [ -f {{ mktemp_output.stdout }}/zopfli ]; then cp {{ mktemp_output.stdout }}/zopfli /usr/local/bin/zopfli; fi
  when: result.rc != 0
