---
- name: Create temp directory for downloading zopfli
  ansible.builtin.tempfile:
    state: directory
    suffix: zopfli
  register: mktemp_output

- name: Check installed
  ansible.builtin.command: /usr/local/bin/zopfli -h
  register: result
  ignore_errors: true
  changed_when: false

- name: Clone zopfli repo
  ansible.builtin.git:
    repo: https://github.com/google/zopfli
    dest: "{{ mktemp_output.path }}"
    force: "yes"
  when: result.rc != 0

- name: Make
  ansible.builtin.command:
    chdir: "{{ mktemp_output.path }}"
    cmd: make -j{{ ansible_processor_cores }}
  when: result.rc != 0

- name: Install
  ansible.builtin.shell: if [ -f {{ mktemp_output.path }}/zopfli ]; then cp {{ mktemp_output.path }}/zopfli /usr/local/bin/zopfli; fi
  when: result.rc != 0
