- name: Create temp directory for downloading electrum
  command: mktemp -d /tmp/electrum.XXXXXX
  register: mktemp_output

- name: Change tmp directory permissions
  file:
    path: "{{ mktemp_output.stdout }}"
    state: directory
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"

- name: Download electrum
  get_url:
    url: "https://download.electrum.org/{{ electrum_version }}/electrum-{{ electrum_version }}-x86_64.AppImage"
    dest: "{{ mktemp_output.stdout }}/electrum-{{ electrum_version }}-x86_64.AppImage"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"

- name: Download ThomasV electrum signature
  get_url:
    url: "https://download.electrum.org/{{ electrum_version }}/electrum-{{ electrum_version }}-x86_64.AppImage.ThomasV.asc"
    dest: "{{ mktemp_output.stdout }}/electrum-{{ electrum_version }}-x86_64.AppImage.ThomasV.asc"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"
    
- name: Download sombernight_releasekey electrum signature
  get_url:
    url: "https://download.electrum.org/{{ electrum_version }}/electrum-{{ electrum_version }}-x86_64.AppImage.sombernight_releasekey.asc"
    dest: "{{ mktemp_output.stdout }}/electrum-{{ electrum_version }}-x86_64.AppImage.sombernight_releasekey.asc"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"
    
- name: Download Emzy electrum signature
  get_url:
    url: "https://raw.githubusercontent.com/spesmilo/electrum-signatures/master/{{ electrum_version }}/electrum-{{ electrum_version }}-x86_64.AppImage/electrum-{{ electrum_version }}-x86_64.AppImage.Emzy.asc"
    dest: "{{ mktemp_output.stdout }}/electrum-{{ electrum_version }}-x86_64.AppImage.Emzy.asc"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"

- name: Get ThomasV GPG key
  shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys  6694D8DE7BE8EE5631BED9502BD5824B7F9470E6 ||
    gpg --keyserver pgp.mit.edu --recv-keys  6694D8DE7BE8EE5631BED9502BD5824B7F9470E6 ||
    gpg --keyserver keyserver.ubuntu.com --recv-keys  6694D8DE7BE8EE5631BED9502BD5824B7F9470E6

- name: Get sombernight_releasekey GPG key
  shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys  4AD64339DFA05E20B3F6AD51E7B748CDAF5E5ED9 ||
    gpg --keyserver pgp.mit.edu --recv-keys  4AD64339DFA05E20B3F6AD51E7B748CDAF5E5ED9 ||
    gpg --keyserver keyserver.ubuntu.com --recv-keys  4AD64339DFA05E20B3F6AD51E7B748CDAF5E5ED9
    
- name: Get Emzy GPG key
  shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC ||
    gpg --keyserver pgp.mit.edu --recv-keys 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC ||
    gpg --keyserver keyserver.ubuntu.com --recv-keys 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC


- name: Verify downloaded archive ThomasV
  command: gpg --verify electrum-{{ electrum_version }}-x86_64.AppImage.ThomasV.asc electrum-{{ electrum_version }}-x86_64.AppImage chdir={{ mktemp_output.stdout }}
  
- name: Verify downloaded archive sombernight_releasekey
  command: gpg --verify electrum-{{ electrum_version }}-x86_64.AppImage.sombernight_releasekey.asc electrum-{{ electrum_version }}-x86_64.AppImage chdir={{ mktemp_output.stdout }}
  
- name: Verify downloaded archive Emzy
  command: gpg --verify electrum-{{ electrum_version }}-x86_64.AppImage.Emzy.asc electrum-{{ electrum_version }}-x86_64.AppImage chdir={{ mktemp_output.stdout }}

- name: directories for electrum appimage
  shell: mkdir -p /home/{{ username }}/{{ apps_dir }}/

- name: Move electrum appimage
  ansible.builtin.copy:
    src: "{{ mktemp_output.stdout }}/electrum-{{ electrum_version }}-x86_64.AppImage"
    dest: "/home/{{ username}}/{{ apps_dir }}/electrum"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"
