---
- name: Install Apparmor
  when: testing != 'true'
  apt:
    pkg:
      - apparmor
      - apparmor-utils
      - apparmor-profiles
    state: present
    update_cache: yes


#- name: copy abstractions
#  copy:
#    src: files/abstractions
#    dest: /etc/apparmor.d/
#    owner: root
#    group: root
#    mode: 0644

#- name: copy tunables
#  copy:
#    src: files/tunables
#    dest: /etc/apparmor.d/
#    owner: root
#    group: root
#    mode: 0644

# - name: ricochet apparmor profile
#   copy:
#     src: files/usr.bin.ricochet
#     dest: /etc/apparmor.d/usr.bin.ricochet
#     owner: root
#     group: root
#     mode: 0644

- name: youtube-dl apparmor profile
  copy:
    src: files/usr.bin.youtube-dl
    dest: /etc/apparmor.d/usr.bin.youtube-dl
    owner: root
    group: root
    mode: 0644

- name: smplayer apparmor profile
  copy:
    src: files/usr.bin.smplayer
    dest: /etc/apparmor.d/usr.bin.smplayer
    owner: root
    group: root
    mode: 0644

- name: Enforce profile for youtube-dl
  when: testing != 'true'
  command: aa-enforce /etc/apparmor.d/usr.bin.youtube-dl

# - name: Enforce profile for ricochet
#   when: testing != 'true'
#   command: aa-enforce /usr/bin/ricochet

- name: Enforce profile for smplayer
  when: testing != 'true'
  command: aa-enforce /etc/apparmor.d/usr.bin.smplayer
