- name: install iptables-persistent
  apt: pkg=iptables-persistent state=present update_cache=true
  notify:
    - start iptables-persistent

# Add user

- name: Add the user 'tor'
  user:
    name: tor
    groups: audio
    shell: /bin/bash
    append: yes
    uid: 1634
    state: present

# Iptables

- name: set firewall rules v4
  copy: src={{ iptables_file_v4 }} dest=/etc/iptables/rules.v4 owner=root group=root mode=644
  notify:
    - restart iptables-persistent

- name: set firewall rules v6
  copy: src={{ iptables_file_v6 }} dest=/etc/iptables/rules.v6 owner=root group=root mode=644
  notify:
    - restart iptables-persistent

- name: ensure iptables-persistent restarted
  notify: 
    - restart iptables-persistent

# Tor

- name: tor package
  package:
    name: tor
    state: present

- name: configure tor to resolve onion hostnames
  blockinfile:
    path: /etc/tor/torrc
    owner: root
    group: root
    mode: 0644
    block: |
      TransPort 9040
      DNSPort 5300
      AutomapHostsOnResolve 1

- name: ensure tor is running
  service: name=tor state=started
