
  #- name: Lookup which is the latest appengine version
  #  shell: curl -s https://cloud.google.com/appengine/downloads | grep -m 1 -oP '(?<=<a href=")https://storage.googleapis.com/appengine-sdks/featured/google_appengine_[\d\.]+.zip(?=">)'  warn=false
  #  register: appengine_url

  - name: Remove appengine directory
    file: path=/home/{{username}}/{{app_engine_dir}}/google_appengine state=absent

  - name: Create appengine directory
    file: path=/home/{{username}}/{{app_engine_dir}}/google_appengine state=directory owner={{username}}

  - name: Create temp file for downloading the appengine .zip
    command: mktemp -d /tmp/appengine.XXXXXXXX
    register: mktemp_output

  - name: Download appengine
    get_url:
      url='{{ appengine_url }}'
      dest='{{mktemp_output.stdout}}/google_appengine.zip'

  - name: Unzip appengine
    unarchive: src={{mktemp_output.stdout}}/google_appengine.zip dest=/home/{{username}}/{{app_engine_dir}}/
