---
- name: Add Emacs APT repository
  ansible.builtin.deb822_repository:
    name: emacs
    types: [deb]
    uris: "https://ppa.launchpadcontent.net/ubuntuhandbook1/emacs/ubuntu"
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF4E48910A020E77056748B745738AE8480447DDF"
    suites: ["{{ ansible_distribution_release }}"]
    components: [main]
    state: present
    enabled: true

- name: Install emacs
  ansible.builtin.apt:
    name: emacs
    state: present

- name: Install emacs-common
  ansible.builtin.apt:
    name: emacs-common
    state: present
