---
- name: install emacs repo
  apt_repository:
    repo: ppa:ubuntuhandbook1/emacs
    update_cache: yes

- name: install emacs
  apt:
    name: emacs
    state: present

- name: install emacs
  apt:
    name: emacs-common
    state: present
