- name: Download rstudio .deb
  get_url: url={{ rstudio_url }} dest=/tmp/rstudio.deb

- name: Install rstudio
  apt: deb="/tmp/rstudio.deb"

# - name: Lookup which is the latest rstudio version
#   shell: curl -s https://www.rstudio.com/products/rstudio/download2/ | grep -Po "(?<=\\.rstudio\\.org/rstudio-)([\\d\\.]+)(?=-{{ rstudio_arch }}\\.deb)" warn=false
#   register: rstudio_ver

#  - name: Create temp dir for downloading the rstudio .deb
#    command: mktemp -d /tmp/ansible.XXXXXXXX
#    register: mktemp_output

#  - name: Download R Studio
#    get_url: url='http://download1.rstudio.org/rstudio-{{ rstudio_ver.stdout }}-{{ rstudio_arch }}.deb' dest='{{mktemp_output.stdout}}/rstudio.deb'

#  - name: Install R Studio
#    apt: deb='{{mktemp_output.stdout}}/rstudio.deb'
