---
- name: Download rstudio .deb
  ansible.builtin.get_url:
    url: "{{ rstudio_url }}"
    dest: /tmp/rstudio.deb
    mode: "0640"

- name: Get GPG key
  ansible.builtin.shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 51C0B5BB19F92D60 ||
    gpg --keyserver pgp.mit.edu --recv-keys 51C0B5BB19F92D60 ||
    gpg --keyserver keyserver.ubuntu.com --recv-keys 51C0B5BB19F92D60

- name: Verify r-studio archive
  ansible.builtin.command: gpg --verify /tmp/rstudio.deb

- name: Install rstudio
  ansible.builtin.apt:
    deb: "/tmp/rstudio.deb"
