---
# - name: Configure the Oracle APT key
#   ansible.builtin.get_url:
#     url: https://www.virtualbox.org/download/oracle_vbox.asc
#     dest: /usr/share/keyrings/oracle_vbox.asc
#     mode: "0640"

# - name: Configure the Oracle APT key
#   ansible.builtin.get_url:
#     url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
#     dest: /usr/share/keyrings/oracle_vbox_2016.asc
#     mode: "0640"

- name: Add Virtualbox APT repository
  ansible.builtin.deb822_repository:
    name: virtualbox
    types: [deb]
    architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    uris: "https://download.virtualbox.org/virtualbox/debian"
    signed_by: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    suites: ["{{ ansible_distribution_release }}"]
    components: [contrib]
    state: present
    enabled: true

- name: Install VirtualBox
  ansible.builtin.apt:
    pkg: virtualbox
    state: present
