---
- name: Create temp directory for downloading borg
  ansible.builtin.tempfile:
    state: directory
    suffix: borg
  register: mktemp_output

- name: Download borg
  ansible.builtin.get_url:
    url: "{{ standalone_download_url }}"
    dest: "{{ mktemp_output.path }}/borg"
    owner: root
    group: root
    mode: "0755"

- name: Download borg signature
  ansible.builtin.get_url:
    url: https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux{{ ansible_userspace_bits }}.asc
    dest: "{{ mktemp_output.path }}/borg.asc"
    owner: "{{ username }}"
    group: root
    mode: "u+rwx,g+rwx,o-rwx"

- name: Get GPG key
  ansible.builtin.shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 6D5BEF9ADD2075805747B70F9F88FB52FAF7B393 ||
    gpg --keyserver pgp.mit.edu --recv-keys 6D5BEF9ADD2075805747B70F9F88FB52FAF7B393 ||
    gpg --keyserver keyserver.ubuntu.com --recv-keys 6D5BEF9ADD2075805747B70F9F88FB52FAF7B393

- name: Verify downloaded archive
  ansible.builtin.command:
    chdir: "{{ mktemp_output.path }}"
    cmd: gpg --verify borg.asc
  tags:
    - skip_ansible_lint

- name: Move borg to /usr/local/bin/
  ansible.builtin.copy:
    src: "{{ mktemp_output.path }}//borg"
    dest: /usr/local/bin/borg
    owner: root
    group: root
    mode: "0755"
    remote_src: "true"
