---
- name: Install apt-transport-https packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - apt-transport-https

- name: Install usbguard package
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - usbguard

- name: Make sure all devices are allowed by default
  ansible.builtin.lineinfile:
    dest: /etc/usbguard/usbguard-daemon.conf
    line: "ImplicitPolicyTarget=allow"
    state: present
    regexp: "^ImplicitPolicyTarget"
    mode: "0640"

- name: Make sure all devices are allowed by default
  ansible.builtin.lineinfile:
    dest: /etc/usbguard/rules.conf
    line: "allow *:*"
    state: present
    create: "yes"
    mode: "0640"

- name: Ensure usbguard is running and enabled as configured.
  ansible.builtin.service:
    name: "usbguard"
    state: started
    enabled: true
  when: docker is undefined
