---
- name: Install apt-transport-https packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - apt-transport-https

- name: Install incron package
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - incron

- name: Make sure has permission to use incron {{ username }}
  ansible.builtin.lineinfile:
    dest: /etc/incron.allow
    line: "{{ username }}"
    state: present

- name: Ensure Incron is running and enabled as configured.
  ansible.builtin.service:
    name: "incron"
    state: started
    enabled: true
  when: docker is undefined
