---
- name: skype | Install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
  - libqt4-dbus
  - libqt4-network
  - libqt4-xml
  - libasound2

- name: add Skype  key
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY

- name: add Skype repo
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    filename: skype-stable

- name: install Skype
  apt:
    name: skypeforlinux
