---
#"generate /etc/hosts.ansible file"
- name: Assemble host file from fragments
  assemble:
    src: "{{ playbook_dir }}/roles/hosts/files"
    remote_src: False
    dest: /etc/hosts.ansible
    delimiter: "# ==========================================================="

- name: "check if original hosts file has a backup"
  stat: "path=/etc/hosts.backup"
  register: etc_hosts_backup

- name: "backup original /etc/hosts"
  command: "cp /etc/hosts /etc/hosts.backup"
  when: etc_hosts_backup.stat.islnk is not defined

- name: "install /etc/hosts.ansible file"
  command: "cp /etc/hosts.ansible /etc/hosts"

# make sure the header looks nice
- blockinfile:
    path: /etc/hosts
    insertbefore: BOF
    content: |
      # This hosts file is a merged collection of hosts from reputable sources,
      # with a dash of crowd sourcing via Github
      #
      # Date: March 08 2019
      # http://winhelp2002.mvps.org/hosts.txt
      # https://github.com/jmdugan/blocklists
      # ===============================================================
      \n
      127.0.0.1 localhost
      127.0.0.1 localhost.localdomain
      127.0.0.1 local
      255.255.255.255 broadcasthost
      ::1 localhost
      fe80::1%lo0 localhost
      0.0.0.0 0.0.0.0
      127.0.1.1 {{ hostname }}
      127.0.0.53 {{ hostname }}
      #0.0.0.0 aire.cdmx.gob.mx
      #0.0.0.0 www.aire.cdmx.gob.mx
      \n
      # Custom host records are listed here.
      #x.x.x.x data.diegovalle.net
      #x.x.x.x data.diegovalle.net
      #x.x.x.x elcri.men
      \n
      # End of custom host records.
