---
- name: Install libsodium
  ansible.builtin.apt:
    pkg: libsodium-dev
    state: present

- name: Install  build-essential
  ansible.builtin.apt:
    pkg: build-essential
    state: present

- name: Install cmake
  ansible.builtin.apt:
    pkg: cmake
    state: present

- name: Create temp directory for downloading minisign
  ansible.builtin.tempfile:
    state: directory
    suffix: minisign
  register: mktemp_output

- name: Check installed
  ansible.builtin.command: /usr/local/bin/minisign
  register: result
  ignore_errors: true
  changed_when: false

- name: Clone minisign repo
  ansible.builtin.git:
    repo: https://github.com/jedisct1/minisign
    dest: "{{ mktemp_output.path }}"
    force: "yes"
  when: result.rc != 0

- name: Make minisign
  ansible.builtin.shell:
    chdir: "{{ mktemp_output.path }}"
    cmd: mkdir build && cd build && cmake .. && make && make install
